/**
 * 食材目录（数据源：data/food_catalog.csv）
 *
 * 注意：本文件后续由 scripts/data-gen.mjs 从 CSV 生成（含 schema 校验）。
 * 修改食材请编辑 CSV 后运行 `npm run data:gen`，不要手改本文件。
 */

export type Category = 'meat' | 'seafood' | 'vegetable' | 'bean' | 'ball' | 'other';

export interface CatalogFood {
  name: string;
  /** 秒 */
  time: number;
  desc: string;
}

export const CATEGORIES: ReadonlyArray<{ id: Category; label: string }> = [
  { id: 'meat', label: '肉类' },
  { id: 'seafood', label: '海鲜' },
  { id: 'vegetable', label: '蔬菜' },
  { id: 'bean', label: '豆制品' },
  { id: 'ball', label: '丸类' },
  { id: 'other', label: '其他' },
];

export const foodDatabase: Record<Category, CatalogFood[]> = {
  meat: [
    { name: '🥩 毛肚', time: 15, desc: '七上八下，口感脆' },
    { name: '🦆 鹅肠', time: 15, desc: '卷曲变脆即可' },
    { name: '🥩 吊龙', time: 15, desc: '（牛里脊）变色即可，勿久煮' },
    { name: '🐑 羊肉卷', time: 30, desc: '卷曲变色无血色' },
    { name: '🥩 牛肉卷', time: 30, desc: '变色即熟，不宜久煮' },
    { name: '👅 牛舌', time: 45, desc: '略微卷曲，颜色变浅' },
    { name: '🥩 牛腩片', time: 45, desc: '肉质变紧，颜色均匀' },
    { name: '💪 牛腱肉', time: 45, desc: '纹理清晰，略带嚼劲' },
    { name: '🐑 鲜切羊肉', time: 45, desc: '肉片变色，无血水' },
    { name: '🫀 黄喉', time: 45, desc: '变白脆弹' },
    { name: '🥩 鲜切牛肉', time: 45, desc: '血色褪去肉质紧' },
    { name: '🥓 腊肉', time: 180, desc: '（若已蒸熟）烫热即可，（生）则需更久' },
    { name: '🦴 牛筋', time: 180, desc: '变软糯，有弹性' },
    { name: '🍖 酥肉', time: 180, desc: '（若已炸熟）吸饱汤汁，外皮略软' },
    { name: '🦆 鸭胗', time: 180, desc: '切花舒展，口感脆' },
    { name: '🐔 鸡胗', time: 180, desc: '切花舒展，口感爽脆' },
    { name: '🥚 鹌鹑蛋', time: 180, desc: '（熟）烫热即可，（生）蛋黄凝固' },
    { name: '🐖 肥肠', time: 180, desc: '（若已卤熟）烫热入味' },
    { name: '🌶️ 双椒牛肉', time: 180, desc: '辣椒颜色鲜亮不脱落' },
    { name: '📚 牛百叶', time: 180, desc: '叶片挺立，口感爽脆' },
    { name: '📚 千层肚', time: 15, desc: '叶片舒展变硬挺' },
  ],
  seafood: [
    { name: '🦪 生蚝', time: 60, desc: '蚝肉边缘卷曲，汁液变白' },
    { name: '🦐 虾', time: 60, desc: '（鲜虾）虾身弯曲变红' },
    { name: '🦀 蟹', time: 240, desc: '（小/切块）蟹壳变红，肉质紧实' },
    { name: '🐚 扇贝', time: 240, desc: '贝肉变白，裙边卷曲' },
    { name: '🐚 鲍鱼', time: 240, desc: '（小/切片）肉质收缩变弹' },
    { name: '🐟 鱼肚', time: 240, desc: '（鱼泡/鱼鳔）泡发后煮至软糯' },
    { name: '🐚 花蛤', time: 240, desc: '贝壳完全张开' },
    { name: '🦑 鱿鱼', time: 300, desc: '变半透明、微皱、有弹性即熟' },
    { name: '🐍 鳝段', time: 360, desc: '肉质收缩无血丝，变紧实' },
    { name: '🐸 牛蛙', time: 360, desc: '（腿/块）肉质变白，紧贴骨头' },
  ],
  vegetable: [
    { name: '🌿 茼蒿', time: 60, desc: '茎秆微软香气浓' },
    { name: '🎍 莴笋', time: 60, desc: '片状断生，保持脆感' },
    { name: '🥬 油麦菜', time: 60, desc: '叶片变软，颜色变深' },
    { name: '🥬 生菜', time: 60, desc: '叶片变软保持青绿' },
    { name: '🌱 韭菜', time: 60, desc: '颜色变深，微软即可' },
    { name: '🥬 娃娃菜', time: 120, desc: '菜帮变软不散' },
    { name: '🥬 大白菜', time: 120, desc: '菜叶软塌，菜帮稍脆' },
    { name: '🌿 芝麻菜', time: 120, desc: '叶片萎蔫，特殊香气' },
    { name: '🌱 红薯苗', time: 120, desc: '（苕尖）叶片软塌，杆茎仍脆' },
    { name: '🥦 花菜', time: 180, desc: '（西兰花/白菜花）颜色鲜艳，软硬适中' },
    { name: '🥒 丝瓜', time: 180, desc: '瓜肉变软透明' },
    { name: '🪷 藕片', time: 180, desc: '口感脆爽或粉糯' },
    { name: '🌊 海带', time: 180, desc: '（鲜/湿）叶片厚实不粘滑' },
    { name: '🍄 木耳', time: 180, desc: '肉质肥厚发亮，口感爽脆' },
    { name: '🌱 海白菜', time: 180, desc: '叶片舒展，口感滑嫩' },
    { name: '🍠 山药', time: 180, desc: '断面呈粉质状，口感绵软' },
    { name: '🥕 胡萝卜', time: 180, desc: '颜色更鲜艳，稍软但仍有脆度' },
    { name: '🎍 贡菜', time: 180, desc: '恢复鲜绿，口感爽脆' },
    { name: '🍄 竹荪', time: 180, desc: '菌帽网状部分吸饱汤汁' },
    { name: '🌼 黄花菜', time: 180, desc: '花蕾变软，颜色鲜黄' },
    { name: '🍄 杏鲍菇', time: 180, desc: '口感Q弹，吸汁' },
    { name: '🍠 红薯', time: 240, desc: '块状需煮透，筷子可穿' },
    { name: '🥔 土豆', time: 240, desc: '片/块边缘透明，中心绵软' },
    { name: '🎍 竹笋', time: 240, desc: '（大块）纤维软化不塞牙' },
    { name: '🌽 玉米', time: 240, desc: '（段）颗粒饱满，香甜' },
    { name: '🍄 茶树菇', time: 300, desc: '纤维软化不塞牙，充分入味' },
    { name: '🍄 香菇', time: 300, desc: '（鲜/干泡发）菌褶吸饱汤汁，菇伞变软' },
    { name: '🍄 平菇', time: 300, desc: '菌伞完全展开，边缘微软' },
    { name: '🍄 金针菇', time: 180, desc: '菌帽分离易嚼，软化入味' },
    { name: '🌱 海带苗', time: 60, desc: '变软变亮' },
  ],
  bean: [
    { name: '🫓 面筋泡', time: 30, desc: '吸饱汤汁，变软即可' },
    { name: '🥠 油豆皮', time: 30, desc: '（薄）软化即可，易吸味' },
    { name: '🥖 老油条', time: 120, desc: '（半软半脆）吸汁后微软即可' },
    { name: '🧈 嫩豆腐', time: 120, desc: '小心易碎，烫热即可' },
    { name: '🥠 千页豆腐', time: 120, desc: '略微膨胀，口感Q弹' },
    { name: '🥠 豆腐皮', time: 120, desc: '（干/鲜）软化吸汁' },
    { name: '🥠 油炸腐竹', time: 120, desc: '吸饱汤汁，微软带韧' },
    { name: '🍜 水晶粉丝', time: 120, desc: '变透明，柔软顺滑' },
    { name: '🍜 土豆粉', time: 120, desc: '变透明，Q弹有嚼劲' },
    { name: '🫓 苕皮', time: 180, desc: '（红薯粉皮）透明软糯' },
    { name: '🍜 宽粉', time: 180, desc: '晶莹剔透，口感Q弹' },
    { name: '🧊 冻豆腐', time: 180, desc: '吸饱汤汁，蜂窝明显' },
    { name: '🍜 龙须面', time: 300, desc: '面条柔软，无硬心' },
    { name: '🍡 年糕', time: 300, desc: '软糯不粘牙' },
    { name: '🥠 腐竹', time: 300, desc: '（干泡发）软韧入味' },
    { name: '🍜 手工面', time: 300, desc: '面条熟透，劲道' },
  ],
  ball: [
    { name: '🥩 牛肉滑', time: 180, desc: '漂浮变色，紧实Q弹' },
    { name: '🦑 墨鱼滑', time: 180, desc: '漂浮变白，紧实Q弹' },
    { name: '🦐 虾滑', time: 180, desc: '漂浮变红，紧实Q弹' },
    { name: '🦀 蟹黄鱼滑', time: 180, desc: '漂浮变色，蟹黄点缀' },
    { name: '🍡 包心丸', time: 240, desc: '漂浮膨胀，内心熟透' },
    { name: '🦐 虾丸', time: 240, desc: '漂浮变大，内部熟透' },
    { name: '🐖 猪肉丸', time: 240, desc: '漂浮变色，按压有弹性' },
    { name: '🍢 四喜丸', time: 240, desc: '体积变大，浮起熟透' },
    { name: '🌿 香菜丸', time: 240, desc: '漂浮，香菜味浓郁' },
    { name: '🦑 墨鱼丸', time: 240, desc: '漂浮变白，Q弹爽口' },
    { name: '🥩 潮州牛肉丸', time: 240, desc: '弹性十足，内部多汁' },
    { name: '🍄 香菇贡丸', time: 240, desc: '漂浮，香菇可见' },
    { name: '💥 撒尿牛丸', time: 240, desc: '膨胀，小心烫嘴' },
    { name: '🐟 鱼丸', time: 240, desc: '漂浮变大，口感Q弹' },
  ],
  other: [
    { name: '🥓 培根', time: 120, desc: '边缘卷曲，油脂溢出' },
    { name: '🍖 火腿', time: 120, desc: '（片状）烫热即可' },
    { name: '🥫 午餐肉', time: 120, desc: '边缘微焦更香' },
    { name: '🦀 蟹肉棒', time: 120, desc: '（蟹柳）散开变色' },
    { name: '🍥 鱼豆腐', time: 120, desc: '膨胀变软，Q弹' },
    { name: '🌭 脆皮肠', time: 180, desc: '肠衣开裂，香气四溢' },
    { name: '🐟 乌鱼卷', time: 180, desc: '（非乌鱼片）变白卷曲' },
    { name: '🥩 坨坨牛肉', time: 180, desc: '（预制）肉块热透入味' },
    { name: '🐟 巴沙鱼片', time: 300, desc: '鱼肉变白，完全熟透' },
    { name: '👅 鸭舌', time: 300, desc: '（鲜）表皮收缩起皱' },
    { name: '🐑 嫩羊肉', time: 300, desc: '（块状/厚片）内部无血色' },
    { name: '🍲 毛血旺', time: 300, desc: '（成品）整体烫热，食材入味' },
    { name: '🥟 虾饺', time: 300, desc: '外皮透明，馅料浮起' },
    { name: '🦴 牛仔骨', time: 300, desc: '肉质离骨，酱香浓郁' },
    { name: '🐔 鸡翅尖', time: 300, desc: '皮肉软糯，易脱骨' },
    { name: '🐖 猪蹄', time: 300, desc: '（预制）皮糯肉烂，热透' },
    { name: '🥟 蛋饺', time: 300, desc: '蛋皮吸汁，内馅熟透' },
    { name: '🐔 鸡翅中', time: 480, desc: '骨肉易分离，完全熟透' },
    { name: '🧠 脑花', time: 480, desc: '（猪脑花）无血丝呈固态，绵密' },
    { name: '🐔 无骨凤爪', time: 480, desc: '胶质软糯，晶莹剔透' },
    { name: '🦴 排骨', time: 480, desc: '（小块）肉质离骨，软烂入味' },
  ],
};

/** 各分类食材数（界面角标/统计用） */
export const FOOD_COUNTS: Record<Category, number> = {
  meat: foodDatabase.meat.length,
  seafood: foodDatabase.seafood.length,
  vegetable: foodDatabase.vegetable.length,
  bean: foodDatabase.bean.length,
  ball: foodDatabase.ball.length,
  other: foodDatabase.other.length,
};
