/**
 * 食材目录（由 scripts/data-gen.mjs 从 data/food_catalog.csv 生成）
 *
 * 本文件为生成物，请勿手改。
 * 修改食材：编辑 CSV 后运行 `npm run data:gen`。
 */

export type Category = 'meat' | 'seafood' | 'vegetable' | 'bean' | 'ball' | 'other';

/** 熟度档位：偏生（绿）/ 适中（黄）/ 偏熟（红） */
export type Doneness = 'rare' | 'medium' | 'wellDone';

export interface CatalogFood {
  name: string;
  /** 适中档时长（秒）——不选档时的默认值 */
  time: number;
  desc: string;
  /** 三档时长（秒）：严格递增 rare < medium < wellDone */
  times: Record<Doneness, number>;
  /** 三档熟成判据（目视确认线索） */
  cues: Record<Doneness, string>;
  /** 偏生档安全提示；空串 = 无额外风险 */
  risk: string;
  /** 涮煮手法提示（一句话）；有明确手法时非空 */
  technique?: string;
  /** 超时后果：hard=多煮即老 / soft=多煮更入味 */
  overtime?: 'hard' | 'soft';
  /** 阶段提示：已过该比例时提醒检查（0~1） */
  midpoint?: number;
}

export const CATEGORIES: ReadonlyArray<{ id: Category; label: string }> = [
  { id: 'meat', label: '肉类' },
  { id: 'seafood', label: '海鲜' },
  { id: 'vegetable', label: '蔬菜' },
  { id: 'bean', label: '豆制品' },
  { id: 'ball', label: '丸类' },
  { id: 'other', label: '其他' },
];

export const foodDatabase: Record<Category, CatalogFood[]> = {
  meat: [
    { name: '🥩 毛肚', time: 15, desc: '七上八下，口感脆', times: { rare: 10, medium: 15, wellDone: 25 }, cues: { rare: '叶片微卷、根须变挺', medium: '七上八下后叶片舒展硬挺、表面挂汁', wellDone: '叶片卷紧发硬' }, risk: '表面短时加热，中心未充分烫透者慎食', technique: '七上八下，抖散快烫', overtime: 'hard' },
    { name: '🦆 鹅肠', time: 15, desc: '卷曲变脆即可', times: { rare: 10, medium: 15, wellDone: 25 }, cues: { rare: '肠身微弯、颜色转粉白', medium: '卷曲变脆、颜色粉白', wellDone: '卷紧发硬、明显缩水' }, risk: '短时涮烫中心可能未全熟', technique: '筷子夹住上下提涮数次', overtime: 'hard' },
    { name: '🥩 吊龙', time: 15, desc: '（牛里脊）变色即可，勿久煮', times: { rare: 10, medium: 15, wellDone: 25 }, cues: { rare: '表面变粉、中心带血丝', medium: '完全变色无血色', wellDone: '颜色变深、开始发柴' }, risk: '偏生为中心带血丝的生熟状态', technique: '大火沸汤微涮', overtime: 'hard' },
    { name: '🐑 羊肉卷', time: 30, desc: '卷曲变色无血色', times: { rare: 20, medium: 30, wellDone: 45 }, cues: { rare: '大部分变色、缝隙微带粉', medium: '卷曲变色、无血色', wellDone: '肉色深、边缘发硬' }, risk: '薄卷回沸慢时中心可能带粉', technique: '肉片泛白散开、脆骨发硬', overtime: 'hard' },
    { name: '🥩 牛肉卷', time: 30, desc: '变色即熟，不宜久煮', times: { rare: 20, medium: 30, wellDone: 45 }, cues: { rare: '变色八九成、留一丝粉', medium: '完全变色无血色', wellDone: '颜色发深、口感变柴' }, risk: '薄卷回沸慢时中心可能带粉', technique: '沸腾处展开快涮', overtime: 'hard' },
    { name: '👅 牛舌', time: 30, desc: '极薄快涮，遇热微缩打卷即熟', times: { rare: 20, medium: 30, wellDone: 45 }, cues: { rare: '遇热微缩、色泽未褪', medium: '微缩打卷、色泽变灰', wellDone: '卷紧发硬' }, risk: '极薄快涮，久煮发韧', technique: '极薄快涮、遇热微缩打卷', overtime: 'hard' },
    { name: '🥩 牛腩片', time: 45, desc: '肉质变紧，颜色均匀', times: { rare: 35, medium: 45, wellDone: 60 }, cues: { rare: '变色大半、纹理微粉', medium: '肉质变紧、颜色均匀', wellDone: '明显收缩、口感发柴' }, risk: '', technique: '肉质变紧、颜色均匀', overtime: 'hard' },
    { name: '💪 牛腱肉', time: 45, desc: '纹理清晰，略带嚼劲', times: { rare: 35, medium: 45, wellDone: 60 }, cues: { rare: '表面变色、断面微粉', medium: '纹理清晰、断面同色', wellDone: '紧实难嚼' }, risk: '', technique: '纹理清晰、略带嚼劲', overtime: 'hard' },
    { name: '🐑 鲜切羊肉', time: 45, desc: '肉片变色，无血水', times: { rare: 35, medium: 45, wellDone: 60 }, cues: { rare: '表面变色、贴骨处微粉', medium: '肉片变色、无血水', wellDone: '收缩发硬' }, risk: '鲜切比肉卷厚，偏生需确认无血水', technique: '肉片变色、无血水', overtime: 'hard' },
    { name: '🫀 黄喉', time: 45, desc: '变白脆弹', times: { rare: 35, medium: 45, wellDone: 60 }, cues: { rare: '开始变白', medium: '变白脆弹、边缘微卷', wellDone: '卷硬咬不动' }, risk: '', technique: '煮至管体向内打卷', overtime: 'hard' },
    { name: '🥩 鲜切牛肉', time: 45, desc: '血色褪去肉质紧', times: { rare: 35, medium: 45, wellDone: 60 }, cues: { rare: '表面变色、中心微红', medium: '血色褪去、肉质变紧', wellDone: '发柴塞牙' }, risk: '偏生为中心微红的生熟状态', technique: '血色褪去、肉质变紧', overtime: 'hard' },
    { name: '🥓 腊肉', time: 180, desc: '（若已蒸熟）烫热即可，（生）则需更久', times: { rare: 150, medium: 180, wellDone: 240 }, cues: { rare: '热透、肥边变透明', medium: '吸味、肥边晶莹', wellDone: '更咸更韧' }, risk: '多为熟制品，生腊肉需煮更久', technique: '烫热即可、肥边变透明', overtime: 'hard' },
    { name: '🦴 牛筋', time: 180, desc: '变软糯，有弹性', times: { rare: 150, medium: 180, wellDone: 240 }, cues: { rare: '变软有弹性', medium: '软糯带弹', wellDone: '软烂粘牙' }, risk: '', technique: '煮至半透明琥珀色、软糯拉丝', overtime: 'hard' },
    { name: '🍖 酥肉', time: 180, desc: '（若已炸熟）吸饱汤汁，外皮略软', times: { rare: 150, medium: 180, wellDone: 240 }, cues: { rare: '外皮微软', medium: '吸饱汤汁、外皮略软', wellDone: '完全软烂' }, risk: '多为炸熟制品', technique: '吸饱汤汁、外皮略软', overtime: 'hard' },
    { name: '🦆 鸭胗', time: 180, desc: '切花舒展，口感脆', times: { rare: 150, medium: 180, wellDone: 240 }, cues: { rare: '切花初展开', medium: '切花舒展、口感脆', wellDone: '变硬发韧' }, risk: '内脏类，偏生未充分加热', technique: '十字花刀翻卷绽开', overtime: 'hard' },
    { name: '🐔 鸡胗', time: 90, desc: '切花舒展，口感爽脆', times: { rare: 60, medium: 90, wellDone: 120 }, cues: { rare: '切花初展开', medium: '切花舒展、口感爽脆', wellDone: '变硬发韧' }, risk: '内脏类，偏生未充分加热', technique: '薄切片受热打卷发硬', overtime: 'hard' },
    { name: '🥚 鹌鹑蛋', time: 180, desc: '（熟）烫热即可，（生）蛋黄凝固', times: { rare: 120, medium: 180, wellDone: 240 }, cues: { rare: '热透', medium: '蛋黄凝固', wellDone: '蛋白发韧' }, risk: '熟蛋烫热即可；生蛋需更久', technique: '熟蛋入锅透热即可', overtime: 'hard' },
    { name: '🐖 肥肠', time: 240, desc: '（若已卤熟）烫热入味', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '热透、开始入味', medium: '烫热入味', wellDone: '更软更入味' }, risk: '多为卤熟制品', technique: '煮至肠壁软糯出油', overtime: 'hard' },
    { name: '🌶️ 双椒牛肉', time: 180, desc: '辣椒颜色鲜亮不脱落', times: { rare: 150, medium: 180, wellDone: 240 }, cues: { rare: '辣椒鲜亮、肉已变色', medium: '辣椒颜色鲜亮不脱落、肉全熟', wellDone: '辣椒软烂' }, risk: '裹浆较厚，中心需时更久', technique: '全熟变色即可捞起', overtime: 'hard' },
    { name: '📚 牛百叶', time: 90, desc: '叶片挺立，口感爽脆', times: { rare: 60, medium: 90, wellDone: 120 }, cues: { rare: '叶片开始挺立', medium: '叶片挺立、口感爽脆', wellDone: '卷硬发韧' }, risk: '', technique: '叶片舒展、稍有卷翘发紧', overtime: 'hard' },
    { name: '📚 千层肚', time: 90, desc: '叶片舒展变硬挺', times: { rare: 60, medium: 90, wellDone: 120 }, cues: { rare: '丝条微挺', medium: '叶片舒展变硬挺', wellDone: '卷紧发硬' }, risk: '表面短时加热，中心未充分烫透者慎食', technique: '百叶丝叶片舒展、稍有卷翘', overtime: 'hard' },
    { name: '🫀 猪黄喉', time: 45, desc: '变白脆弹', times: { rare: 30, medium: 45, wellDone: 60 }, cues: { rare: '开始变白', medium: '变白脆弹、边缘微卷', wellDone: '卷硬咬不动' }, risk: '', technique: '煮至管体向内打卷', overtime: 'hard' },
    { name: '🫀 牛黄喉', time: 90, desc: '变白脆弹', times: { rare: 60, medium: 90, wellDone: 120 }, cues: { rare: '开始变白', medium: '变白脆弹、边缘微卷', wellDone: '卷硬咬不动' }, risk: '', technique: '煮至管体向内打卷', overtime: 'hard' },
    { name: '🥩 腰片', time: 20, desc: '由红润变灰白、边缘微翘即熟', times: { rare: 15, medium: 20, wellDone: 30 }, cues: { rare: '表面微变、中心红润', medium: '红润转灰白、边缘微翘', wellDone: '收缩发硬' }, risk: '内脏类，偏生未充分加热', technique: '单片夹住浸入沸油快涮', overtime: 'hard' },
    { name: '🩸 鸭血', time: 360, desc: '完全浮起、内部出现细小气孔即熟', times: { rare: 300, medium: 360, wellDone: 480 }, cues: { rare: '沉底未浮', medium: '完全浮起、块体膨胀', wellDone: '内部气孔明显' }, risk: '务必煮透（寄生虫风险）', technique: '冷锅或小火慢煨', overtime: 'hard', midpoint: 0.5 },
    { name: '🌶️ 麻辣牛肉', time: 180, desc: '需煮透断生，中火翻滚不易煮柴', times: { rare: 120, medium: 180, wellDone: 240 }, cues: { rare: '外层浆壳未化', medium: '浆壳化开、肉全熟', wellDone: '肉质发柴' }, risk: '裹浆较厚，中心需时更久', technique: '中火翻滚煮透断生', overtime: 'hard' },
    { name: '🥩 滑嫩牛肉', time: 90, desc: '浮起受热均匀、表面滑嫩发亮时捞出', times: { rare: 60, medium: 90, wellDone: 120 }, cues: { rare: '表面微变、浆壳未化', medium: '浮起受热均匀、表面滑嫩发亮', wellDone: '肉质发柴' }, risk: '上浆保护，偏生中心可能带粉', technique: '浮起受热均匀即捞', overtime: 'hard' },
    { name: '🦴 牛骨髓', time: 240, desc: '由半透生肉质感转为乳白凝固脂膏状即熟', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '半透生肉质感', medium: '乳白凝固脂膏状、筷扎不散', wellDone: '更实' }, risk: '', technique: '漏勺中小火慢煨', overtime: 'hard', midpoint: 0.5 },
    { name: '🐖 猪天堂', time: 90, desc: '软骨受热两端翘起成月牙形、咬断有清脆声即可', times: { rare: 60, medium: 90, wellDone: 120 }, cues: { rare: '受热未翘', medium: '两端翘起成月牙形、色泽乳白', wellDone: '发硬' }, risk: '', technique: '受热两端翘起成月牙形', overtime: 'hard' },
    { name: '👅 牛舌片', time: 30, desc: '极薄快涮，遇热微缩打卷即熟', times: { rare: 20, medium: 30, wellDone: 45 }, cues: { rare: '遇热微缩、色泽未褪', medium: '微缩打卷、色泽变灰', wellDone: '卷紧发硬' }, risk: '极薄快涮，久煮发韧', technique: '极薄快涮、遇热微缩打卷', overtime: 'hard' },
    { name: '🌶️ 泡椒牛肉', time: 120, desc: '牛肉全熟包裹酸辣泡椒，咬开小心内包热酸汁烫嘴', times: { rare: 90, medium: 120, wellDone: 150 }, cues: { rare: '牛肉未全熟', medium: '牛肉全熟包裹酸辣泡椒', wellDone: '肉质发柴' }, risk: '裹浆较厚，中心需时更久', technique: '牛肉全熟包裹酸辣泡椒', overtime: 'hard' },
    { name: '🦴 猪鼻筋', time: 180, desc: '半透筋膜受热缩紧发白卷曲，软糯带脆劲', times: { rare: 120, medium: 180, wellDone: 240 }, cues: { rare: '筋膜未缩紧', medium: '半透筋膜缩紧发白卷曲', wellDone: '发硬' }, risk: '', technique: '半透筋膜缩紧发白卷曲', overtime: 'hard' },
    { name: '🐔 乌鸡卷', time: 45, desc: '薄切刨卷，完全变色舒展即捞', times: { rare: 30, medium: 45, wellDone: 60 }, cues: { rare: '薄卷未舒展', medium: '完全变色舒展', wellDone: '肉碎发柴' }, risk: '薄卷回沸慢时中心可能带粉', technique: '薄切刨卷、完全变色舒展', overtime: 'hard' },
    { name: '🥩 匙柄', time: 18, desc: '中间一条细肉筋微缩受热，变白即可', times: { rare: 12, medium: 18, wellDone: 30 }, cues: { rare: '中间肉筋未缩', medium: '中间细肉筋微缩受热、变白', wellDone: '发柴' }, risk: '', technique: '中间细肉筋微缩受热变白', overtime: 'hard' },
    { name: '🫀 牛脆管', time: 120, desc: '白管微缩变硬，嚼感与黄喉类似但更具韧脆度', times: { rare: 90, medium: 120, wellDone: 150 }, cues: { rare: '白管未缩', medium: '白管微缩变硬', wellDone: '发硬' }, risk: '', technique: '白管微缩变硬', overtime: 'hard' },
    { name: '🐔 鸡肾', time: 240, desc: '必须完全煮透至球体鼓圆、内部蛋白彻底凝固无生红', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '球体未鼓圆', medium: '球体鼓圆、内部蛋白凝固', wellDone: '发硬' }, risk: '务必煮透（寄生虫风险）', technique: '煮透至球体鼓圆、蛋白凝固', overtime: 'hard' },
    { name: '🥩 牛胸口油', time: 180, desc: '脂肪受热紧缩打卷、逼出多余油脂，入口嘎吱脆香', times: { rare: 120, medium: 180, wellDone: 240 }, cues: { rare: '脂肪未缩', medium: '脂肪受热紧缩打卷、逼出油脂', wellDone: '发硬' }, risk: '', technique: '脂肪受热紧缩打卷', overtime: 'hard' },
    { name: '🥩 猪肚丝', time: 120, desc: '生鲜肚丝变白卷曲微挺即熟，熟肚丝烫1分钟即可', times: { rare: 90, medium: 120, wellDone: 150 }, cues: { rare: '肚丝未变白', medium: '变白卷曲微挺', wellDone: '发硬' }, risk: '生鲜肚丝偏生未充分加热', technique: '变白卷曲微挺即熟', overtime: 'hard' },
    { name: '🌶️ 香菜牛肉', time: 90, desc: '外层肉卷变灰断生、内部香菜尚带生脆气时捞出', times: { rare: 60, medium: 90, wellDone: 120 }, cues: { rare: '外层肉卷未变灰', medium: '外层肉卷变灰断生、内部香菜带生脆', wellDone: '肉质发柴' }, risk: '裹浆较厚，中心需时更久', technique: '外层变灰断生、内部香菜带生脆', overtime: 'hard' },
    { name: '🐔 鸭心', time: 180, desc: '花刀完全张开呈球状、深红褪去微挺即可', times: { rare: 120, medium: 180, wellDone: 240 }, cues: { rare: '花刀未张开', medium: '花刀完全张开呈球状、深红褪去', wellDone: '发硬' }, risk: '内脏类，偏生未充分加热', technique: '花刀完全张开呈球状', overtime: 'hard' },
    { name: '🥩 牛肚仁', time: 90, desc: '厚实但极其脆嫩，变白挺起即可', times: { rare: 60, medium: 90, wellDone: 120 }, cues: { rare: '未变白', medium: '变白挺起', wellDone: '发韧' }, risk: '表面短时加热，中心未充分烫透者慎食', technique: '变白挺起即可，久煮发韧', overtime: 'hard' },
    { name: '🐔 鸭掌筋', time: 180, desc: '筋条遇热缩成透亮硬挺状，耐嚼弹牙', times: { rare: 120, medium: 180, wellDone: 240 }, cues: { rare: '筋条未缩', medium: '筋条遇热缩成透亮硬挺状', wellDone: '发硬' }, risk: '', technique: '筋条遇热缩成透亮硬挺', overtime: 'hard' },
    { name: '🐔 鸭肾', time: 240, desc: '必须完全煮透至球体鼓圆、内部蛋白彻底凝固无生红', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '球体未鼓圆', medium: '球体鼓圆、内部蛋白凝固', wellDone: '发硬' }, risk: '务必煮透（寄生虫风险）', technique: '煮透至球体鼓圆、蛋白凝固', overtime: 'hard' },
  ],
  seafood: [
    { name: '🦪 生蚝', time: 60, desc: '蚝肉边缘卷曲，汁液变白', times: { rare: 45, medium: 60, wellDone: 90 }, cues: { rare: '边缘微卷、汁液转白', medium: '边缘卷曲明显、汁液变白', wellDone: '收缩变硬' }, risk: '贝类，偏生有副溶血性弧菌风险', technique: '蚝肉边缘卷曲、汁液变白', overtime: 'hard', midpoint: 0.5 },
    { name: '🦐 虾', time: 60, desc: '（鲜虾）虾身弯曲变红', times: { rare: 45, medium: 60, wellDone: 90 }, cues: { rare: '虾身开始变红弯曲', medium: '虾身弯曲成C形、通体变红', wellDone: '卷成O形、肉质发紧' }, risk: '甲壳类，偏生有副溶血性弧菌风险', technique: '虾身弯曲成C形即捞', overtime: 'hard', midpoint: 0.5 },
    { name: '🦀 蟹', time: 240, desc: '（小/切块）蟹壳变红，肉质紧实', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '壳转橙红', medium: '蟹壳变红、肉质紧实', wellDone: '肉老离壳' }, risk: '蟹类务必煮透（肺吸虫/菌）', technique: '蟹壳变红、肉质紧实', overtime: 'hard', midpoint: 0.5 },
    { name: '🐚 扇贝', time: 240, desc: '贝肉变白，裙边卷曲', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '贝肉变白', medium: '贝肉变白、裙边卷曲', wellDone: '缩小变硬' }, risk: '贝类，偏生有副溶血性弧菌风险', technique: '贝肉变白、裙边卷曲', overtime: 'hard', midpoint: 0.5 },
    { name: '🐚 鲍鱼', time: 240, desc: '（小/切片）肉质收缩变弹', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '肉质收缩变弹', medium: '边缘卷起、肉质紧弹', wellDone: '橡皮口感' }, risk: '贝类，偏生有副溶血性弧菌风险', technique: '肉质收缩变弹', overtime: 'hard', midpoint: 0.5 },
    { name: '🐟 鱼肚', time: 240, desc: '（鱼泡/鱼鳔）泡发后煮至软糯', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '变软', medium: '软糯吸汁', wellDone: '更软烂' }, risk: '', technique: '泡发后煮至软糯', overtime: 'hard', midpoint: 0.5 },
    { name: '🐚 花蛤', time: 240, desc: '贝壳完全张开', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '大部分开口', medium: '贝壳完全张开', wellDone: '肉缩小变硬' }, risk: '未开口的个别丢弃；贝类偏生有风险', technique: '贝壳完全张开', overtime: 'hard', midpoint: 0.5 },
    { name: '🦑 鱿鱼', time: 90, desc: '变半透明、微皱、有弹性即熟', times: { rare: 60, medium: 90, wellDone: 120 }, cues: { rare: '开始变半透明', medium: '变半透明、微皱、有弹性', wellDone: '明显收缩发硬' }, risk: '头足类，未熟透易致消化不良', technique: '刀口深卷成麦穗形', overtime: 'hard', midpoint: 0.5 },
    { name: '🐍 鳝段', time: 300, desc: '肉质收缩无血丝，变紧实', times: { rare: 240, medium: 300, wellDone: 360 }, cues: { rare: '肉质收缩、贴骨处微红', medium: '肉质收缩无血丝、变紧实', wellDone: '肉离骨发硬' }, risk: '鳝鱼务必全熟（类组胺/寄生虫）', technique: '中火煮透至血色褪净', overtime: 'hard', midpoint: 0.5 },
    { name: '🐸 牛蛙', time: 360, desc: '（腿/块）肉质变白，紧贴骨头', times: { rare: 300, medium: 360, wellDone: 420 }, cues: { rare: '肉变白、贴骨处微红', medium: '肉质变白、紧贴骨头', wellDone: '肉离骨发柴' }, risk: '蛙类务必全熟（裂头蚴风险）', technique: '中大火彻底煮透', overtime: 'hard', midpoint: 0.5 },
    { name: '🐟 耗儿鱼', time: 360, desc: '需中火煮透，鱼肉与主刺脱离即熟', times: { rare: 300, medium: 360, wellDone: 480 }, cues: { rare: '鱼肉未收缩', medium: '鱼肉收缩与主刺脱离、呈蒜瓣状雪白', wellDone: '肉离骨发硬' }, risk: '务必煮透（寄生虫风险）', technique: '中火煮透至鱼骨脱离', overtime: 'hard', midpoint: 0.5 },
    { name: '🦑 鱿鱼卷', time: 90, desc: '刀口深卷成麦穗形、质地转脆硬即可', times: { rare: 60, medium: 90, wellDone: 120 }, cues: { rare: '开始卷曲', medium: '刀口深卷成麦穗形、质地脆硬', wellDone: '明显收缩发硬' }, risk: '头足类，未熟透易致消化不良', technique: '刀口深卷成麦穗形', overtime: 'hard', midpoint: 0.5 },
    { name: '🐟 黑鱼片', time: 45, desc: '薄鱼片遇沸汤极速泛白蜷曲即熟', times: { rare: 30, medium: 45, wellDone: 60 }, cues: { rare: '遇热未泛白', medium: '薄鱼片极速泛白蜷曲', wellDone: '肉质发紧' }, risk: '水产建议全熟', technique: '薄鱼片遇沸汤极速泛白', overtime: 'hard' },
    { name: '🐟 泥鳅', time: 420, desc: '必须中火彻底煮透，鱼肉与主脊椎骨脱离', times: { rare: 360, medium: 420, wellDone: 480 }, cues: { rare: '鱼肉未收缩', medium: '鱼肉紧缩发裂、与主脊椎骨脱离', wellDone: '肉离骨发硬' }, risk: '务必煮透（寄生虫风险）', technique: '中火彻底煮透', overtime: 'hard', midpoint: 0.5 },
    { name: '🐟 带鱼段', time: 300, desc: '鱼身银鳞微收、鱼肉转瓷白紧实即熟', times: { rare: 240, medium: 300, wellDone: 360 }, cues: { rare: '银鳞未收', medium: '鱼身银鳞微收、鱼肉瓷白紧实', wellDone: '肉离骨发硬' }, risk: '水产务必全熟', technique: '切忌猛火翻搅致碎', overtime: 'hard', midpoint: 0.5 },
    { name: '🐟 龙利鱼片', time: 180, desc: '白肉微浮起、用筷能轻掐断即熟', times: { rare: 120, medium: 180, wellDone: 240 }, cues: { rare: '白肉未浮起', medium: '白肉微浮起、用筷能轻掐断', wellDone: '肉质发紧' }, risk: '水产务必全熟', technique: '白肉微浮起轻掐断即熟', overtime: 'hard' },
    { name: '🐙 八爪鱼', time: 90, desc: '头部圆鼓、爪子全部回缩成菊花球即捞', times: { rare: 60, medium: 90, wellDone: 120 }, cues: { rare: '头部未鼓', medium: '头部圆鼓、爪子回缩成菊花球', wellDone: '发硬' }, risk: '', technique: '爪子全部回缩成菊花球', overtime: 'hard', midpoint: 0.5 },
    { name: '🦑 墨鱼仔', time: 180, desc: '圆肚胀鼓、小触角紧密内蜷成球状，咬之爆汁爽脆', times: { rare: 120, medium: 180, wellDone: 240 }, cues: { rare: '圆肚未胀', medium: '圆肚胀鼓、小触角内蜷成球状', wellDone: '发硬' }, risk: '', technique: '圆肚胀鼓、触角内蜷成球', overtime: 'hard', midpoint: 0.5 },
    { name: '🐟 黄辣丁', time: 360, desc: '小火煨煮至鱼鳍立起、鱼皮微开裂、肉质极嫩滑', times: { rare: 300, medium: 360, wellDone: 420 }, cues: { rare: '鱼鳍未立', medium: '鱼鳍立起、鱼皮微开裂', wellDone: '肉离骨发硬' }, risk: '务必煮透（寄生虫风险）', technique: '小火煨煮至鱼鳍立起', overtime: 'hard', midpoint: 0.5 },
    { name: '🐟 乌鱼片', time: 45, desc: '薄鱼片遇沸汤极速泛白蜷曲即熟', times: { rare: 30, medium: 45, wellDone: 60 }, cues: { rare: '遇热未泛白', medium: '薄鱼片极速泛白蜷曲', wellDone: '肉质发紧' }, risk: '水产建议全熟', technique: '薄鱼片遇沸汤极速泛白', overtime: 'hard' },
    { name: '🦐 基围虾', time: 60, desc: '（鲜虾）虾身弯曲变红', times: { rare: 45, medium: 60, wellDone: 90 }, cues: { rare: '虾身开始变红弯曲', medium: '虾身弯曲成C形、通体深红', wellDone: '卷成O形、肉质发紧' }, risk: '甲壳类，偏生有副溶血性弧菌风险', technique: '虾身弯曲成C形即捞', overtime: 'hard', midpoint: 0.5 },
    { name: '🦐 黑虎虾', time: 60, desc: '（鲜虾）虾身弯曲变红', times: { rare: 45, medium: 60, wellDone: 90 }, cues: { rare: '虾身开始变红弯曲', medium: '虾身弯曲成C形、通体深红', wellDone: '卷成O形、肉质发紧' }, risk: '甲壳类，偏生有副溶血性弧菌风险', technique: '虾身弯曲成C形即捞', overtime: 'hard', midpoint: 0.5 },
  ],
  vegetable: [
    { name: '🌿 茼蒿', time: 25, desc: '茎秆微软香气浓', times: { rare: 15, medium: 25, wellDone: 45 }, cues: { rare: '叶片变软', medium: '茎秆微软、香气浓', wellDone: '软烂' }, risk: '无生食风险，按口感选档', technique: '中火处翻两下断生即捞', overtime: 'hard' },
    { name: '🎍 莴笋', time: 60, desc: '片状断生，保持脆感', times: { rare: 45, medium: 60, wellDone: 90 }, cues: { rare: '片状断生、保持脆感', medium: '半透明、脆嫩', wellDone: '软而不脆' }, risk: '无生食风险，按口感选档', technique: '青绿半透明为清脆断生', overtime: 'hard' },
    { name: '🥬 油麦菜', time: 60, desc: '叶片变软，颜色变深', times: { rare: 45, medium: 60, wellDone: 90 }, cues: { rare: '叶片变软、颜色变深', medium: '叶软色深', wellDone: '软烂' }, risk: '无生食风险，按口感选档', technique: '叶片变软、颜色变深', overtime: 'hard' },
    { name: '🥬 生菜', time: 60, desc: '叶片变软保持青绿', times: { rare: 45, medium: 60, wellDone: 90 }, cues: { rare: '叶片变软保持青绿', medium: '变软转深绿', wellDone: '软烂' }, risk: '无生食风险，按口感选档', technique: '叶片变软保持青绿', overtime: 'hard' },
    { name: '🌱 韭菜', time: 60, desc: '颜色变深，微软即可', times: { rare: 45, medium: 60, wellDone: 90 }, cues: { rare: '颜色变深', medium: '微软、色深', wellDone: '软烂' }, risk: '无生食风险，按口感选档', technique: '颜色变深、微软即可', overtime: 'hard' },
    { name: '🥬 娃娃菜', time: 120, desc: '菜帮变软不散', times: { rare: 90, medium: 120, wellDone: 180 }, cues: { rare: '菜帮微软', medium: '菜帮变软、叶不散', wellDone: '软烂' }, risk: '无生食风险，按口感选档', technique: '中火少浮油处烫，防过辣', overtime: 'hard', midpoint: 0.5 },
    { name: '🥬 大白菜', time: 120, desc: '菜叶软塌，菜帮稍脆', times: { rare: 90, medium: 120, wellDone: 180 }, cues: { rare: '菜叶软、菜帮稍脆', medium: '叶软塌、菜帮微软', wellDone: '软烂' }, risk: '无生食风险，按口感选档', technique: '菜叶软塌、菜帮稍脆', overtime: 'hard', midpoint: 0.5 },
    { name: '🌿 芝麻菜', time: 120, desc: '叶片萎蔫，特殊香气', times: { rare: 90, medium: 120, wellDone: 180 }, cues: { rare: '叶片萎蔫', medium: '萎蔫、香气释放', wellDone: '软烂' }, risk: '无生食风险，按口感选档', technique: '叶片萎蔫、特殊香气', overtime: 'hard' },
    { name: '🌱 红薯苗', time: 120, desc: '（苕尖）叶片软塌，杆茎仍脆', times: { rare: 90, medium: 120, wellDone: 180 }, cues: { rare: '叶片软塌、杆茎仍脆', medium: '叶软杆脆', wellDone: '全软' }, risk: '无生食风险，按口感选档', technique: '叶片软塌、杆茎仍脆', overtime: 'hard' },
    { name: '🥦 花菜', time: 180, desc: '（西兰花/白菜花）颜色鲜艳，软硬适中', times: { rare: 150, medium: 180, wellDone: 240 }, cues: { rare: '颜色鲜艳、稍硬', medium: '颜色鲜艳、软硬适中', wellDone: '软面' }, risk: '建议煮软些，利于消化', technique: '颜色鲜艳、软硬适中', overtime: 'hard', midpoint: 0.5 },
    { name: '🥒 丝瓜', time: 180, desc: '瓜肉变软透明', times: { rare: 150, medium: 180, wellDone: 240 }, cues: { rare: '瓜肉开始变软', medium: '瓜肉变软透明', wellDone: '软烂' }, risk: '无生食风险，按口感选档', technique: '瓜肉变软透明', overtime: 'hard', midpoint: 0.5 },
    { name: '🪷 藕片', time: 180, desc: '口感脆爽或粉糯', times: { rare: 120, medium: 180, wellDone: 240 }, cues: { rare: '口感脆爽', medium: '脆中带面', wellDone: '粉糯' }, risk: '无生食风险，按口感选档', technique: '断生微透即保持脆甜', overtime: 'hard', midpoint: 0.5 },
    { name: '🌊 海带', time: 180, desc: '（鲜/湿）叶片厚实不粘滑', times: { rare: 150, medium: 180, wellDone: 240 }, cues: { rare: '厚实不粘滑', medium: '叶片厚实、口感弹', wellDone: '软糯' }, risk: '无生食风险，按口感选档', technique: '叶片厚实不粘滑', overtime: 'hard', midpoint: 0.5 },
    { name: '🍄 木耳', time: 180, desc: '肉质肥厚发亮，口感爽脆', times: { rare: 120, medium: 180, wellDone: 240 }, cues: { rare: '肥厚发亮', medium: '肉质肥厚发亮、爽脆', wellDone: '软韧' }, risk: '建议煮透', technique: '表面光滑油亮、耳瓣伸展', overtime: 'hard', midpoint: 0.5 },
    { name: '🌱 海白菜', time: 180, desc: '叶片舒展，口感滑嫩', times: { rare: 150, medium: 180, wellDone: 240 }, cues: { rare: '叶片舒展', medium: '舒展滑嫩', wellDone: '软烂' }, risk: '无生食风险，按口感选档', technique: '叶片舒展、口感滑嫩', overtime: 'hard' },
    { name: '🍠 山药', time: 180, desc: '断面呈粉质状，口感绵软', times: { rare: 150, medium: 180, wellDone: 240 }, cues: { rare: '断面刚转粉', medium: '断面粉质、口感绵软', wellDone: '更面' }, risk: '务必断生，生黏液刺激口腔', technique: '断面呈粉质状、口感绵软', overtime: 'hard', midpoint: 0.5 },
    { name: '🥕 胡萝卜', time: 180, desc: '颜色更鲜艳，稍软但仍有脆度', times: { rare: 150, medium: 180, wellDone: 240 }, cues: { rare: '颜色鲜艳、稍脆', medium: '稍软带脆', wellDone: '软面' }, risk: '无生食风险，按口感选档', technique: '颜色更鲜艳、稍软带脆', overtime: 'hard', midpoint: 0.5 },
    { name: '🎍 贡菜', time: 120, desc: '恢复鲜绿，口感爽脆', times: { rare: 90, medium: 120, wellDone: 180 }, cues: { rare: '恢复鲜绿', medium: '鲜绿爽脆', wellDone: '软而不脆' }, risk: '无生食风险，按口感选档', technique: '变深翠绿且微透即捞', overtime: 'hard' },
    { name: '🍄 竹荪', time: 90, desc: '菌帽网状部分吸饱汤汁', times: { rare: 60, medium: 90, wellDone: 120 }, cues: { rare: '开始吸汁', medium: '菌帽网状吸饱汤汁', wellDone: '软烂' }, risk: '', technique: '几经翻滚、吸饱汤汁变软', overtime: 'hard' },
    { name: '🌼 黄花菜', time: 180, desc: '花蕾变软，颜色鲜黄', times: { rare: 150, medium: 180, wellDone: 240 }, cues: { rare: '花蕾变软', medium: '变软、颜色鲜黄', wellDone: '软烂' }, risk: '干品需泡发；务必煮透', technique: '花蕾变软、颜色鲜黄', overtime: 'hard', midpoint: 0.5 },
    { name: '🍄 杏鲍菇', time: 240, desc: '口感Q弹，吸汁', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '边缘开始变软', medium: '口感Q弹、吸汁', wellDone: '软嫩' }, risk: '建议煮透', technique: '切片煮透转软', overtime: 'hard', midpoint: 0.5 },
    { name: '🍠 红薯', time: 240, desc: '块状需煮透，筷子可穿', times: { rare: 210, medium: 240, wellDone: 300 }, cues: { rare: '筷子可插入', medium: '筷子可穿透、中心绵', wellDone: '粉烂' }, risk: '块状需煮透', technique: '块状需煮透、筷子可穿', overtime: 'hard', midpoint: 0.5 },
    { name: '🥔 土豆', time: 240, desc: '片/块边缘透明，中心绵软', times: { rare: 210, medium: 240, wellDone: 300 }, cues: { rare: '边缘透明、中心稍硬', medium: '边缘透明、中心绵软', wellDone: '散开' }, risk: '片/块均需煮透', technique: '薄片通透即捞，厚片多煮', overtime: 'hard', midpoint: 0.5 },
    { name: '🎍 竹笋', time: 240, desc: '（大块）纤维软化不塞牙', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '纤维稍软', medium: '纤维软化不塞牙', wellDone: '更软' }, risk: '务必煮透（草酸/氰苷）', technique: '笋肉纤维稍煮透、涩味尽褪', overtime: 'hard', midpoint: 0.5 },
    { name: '🌽 玉米', time: 240, desc: '（段）颗粒饱满，香甜', times: { rare: 210, medium: 240, wellDone: 300 }, cues: { rare: '颗粒饱满', medium: '饱满香甜', wellDone: '更甜软' }, risk: '无生食风险，按口感选档', technique: '段状颗粒饱满、香甜', overtime: 'hard', midpoint: 0.5 },
    { name: '🍄 茶树菇', time: 300, desc: '纤维软化不塞牙，充分入味', times: { rare: 270, medium: 300, wellDone: 360 }, cues: { rare: '纤维稍软', medium: '软化不塞牙、入味', wellDone: '软烂' }, risk: '建议煮透', technique: '纤维软化不塞牙、充分入味', overtime: 'hard', midpoint: 0.5 },
    { name: '🍄 香菇', time: 300, desc: '（鲜/干泡发）菌褶吸饱汤汁，菇伞变软', times: { rare: 240, medium: 300, wellDone: 360 }, cues: { rare: '菇伞开始变软', medium: '菌褶吸汁、菇伞变软', wellDone: '软烂' }, risk: '建议煮透', technique: '菇盖发软多汁即可', overtime: 'hard', midpoint: 0.5 },
    { name: '🍄 平菇', time: 240, desc: '菌伞完全展开，边缘微软', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '菌伞展开', medium: '完全展开、边缘微软', wellDone: '软烂' }, risk: '建议煮透', technique: '完全煮软、压出生水', overtime: 'hard', midpoint: 0.5 },
    { name: '🍄 金针菇', time: 180, desc: '菌帽分离易嚼，软化入味', times: { rare: 120, medium: 180, wellDone: 240 }, cues: { rare: '菌帽分离', medium: '软化入味、易嚼', wellDone: '软烂' }, risk: '建议煮透', technique: '菇体由挺立转为完全伏软', overtime: 'hard', midpoint: 0.5 },
    { name: '🌱 海带苗', time: 30, desc: '变软变亮', times: { rare: 20, medium: 30, wellDone: 45 }, cues: { rare: '入汤未变色', medium: '变翠绿、软亮', wellDone: '软烂' }, risk: '无生食风险，按口感选档', technique: '入沸汤变翠绿色即起', overtime: 'hard' },
    { name: '🌿 豌豆尖', time: 10, desc: '极速飞水，变深翠绿立刻起锅', times: { rare: 5, medium: 10, wellDone: 15 }, cues: { rare: '入汤未变色', medium: '变深翠绿、脆嫩', wellDone: '软烂' }, risk: '无生食风险，按口感选档', technique: '筷子一摁变深翠绿立刻起锅', overtime: 'hard' },
    { name: '🍄 绣球菌', time: 120, desc: '花瓣由白微透，口感近似脆海蜇', times: { rare: 90, medium: 120, wellDone: 150 }, cues: { rare: '花瓣未透', medium: '花瓣由白微透、口感似脆海蜇', wellDone: '软烂' }, risk: '建议煮透', technique: '花瓣由白微透即捞', overtime: 'hard' },
    { name: '🥕 白萝卜', time: 240, desc: '建议在吃完荤菜后下锅，吸油解腻、回甘清甜', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '边缘未透', medium: '边缘透明软化', wellDone: '软烂' }, risk: '无生食风险，按口感选档', technique: '吃完荤菜后下锅，吸油解腻', overtime: 'hard', midpoint: 0.5 },
    { name: '🌱 折耳根', time: 60, desc: '根部30～60秒脆且味浓，3分钟以上粉软味淡', times: { rare: 30, medium: 60, wellDone: 180 }, cues: { rare: '根部未透', medium: '根部脆且味浓', wellDone: '粉软味淡' }, risk: '特殊风味，按耐受度调整', technique: '根部30~60秒脆且味浓' },
    { name: '🥒 冬瓜', time: 240, desc: '瓜肉边缘完全透明软化，入口化水吸油', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '瓜肉未透', medium: '瓜肉边缘完全透明软化', wellDone: '软烂' }, risk: '无生食风险，按口感选档', technique: '瓜肉边缘完全透明软化', overtime: 'hard', midpoint: 0.5 },
    { name: '🌿 西洋菜', time: 30, desc: '沸汤快捞，变绿即食，清爽解腻', times: { rare: 15, medium: 30, wellDone: 45 }, cues: { rare: '入汤未变色', medium: '变绿、清爽', wellDone: '软烂' }, risk: '无生食风险，按口感选档', technique: '沸汤快捞，变绿即食', overtime: 'hard' },
    { name: '🍄 羊肚菌', time: 240, desc: '菌腔吸饱汤汁膨软，菌褶微缩、香气四溢即可捞起', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '菌腔未吸汁', medium: '菌腔吸饱汤汁膨软、菌褶微缩', wellDone: '软烂' }, risk: '建议煮透', technique: '菌腔吸饱汤汁膨软', overtime: 'hard', midpoint: 0.5 },
    { name: '🌊 海带芽', time: 30, desc: '薄嫩无比，入沸汤变翠绿色即起', times: { rare: 20, medium: 30, wellDone: 45 }, cues: { rare: '入汤未变色', medium: '变翠绿、软亮', wellDone: '软烂' }, risk: '无生食风险，按口感选档', technique: '入沸汤变翠绿色即起', overtime: 'hard' },
  ],
  bean: [
    { name: '🫓 面筋泡', time: 30, desc: '吸饱汤汁，变软即可', times: { rare: 20, medium: 30, wellDone: 60 }, cues: { rare: '开始吸汁', medium: '吸饱汤汁、变软', wellDone: '更软' }, risk: '无生食风险，按口感选档', technique: '吸饱汤汁、变软即可', overtime: 'hard' },
    { name: '🥠 油豆皮', time: 30, desc: '（薄）软化即可，易吸味', times: { rare: 20, medium: 30, wellDone: 60 }, cues: { rare: '软化', medium: '微软吸味', wellDone: '软烂' }, risk: '易吸味，久煮易散', technique: '下锅软化吸汤即起', overtime: 'hard' },
    { name: '🥖 老油条', time: 10, desc: '（半软半脆）吸汁后微软即可', times: { rare: 6, medium: 10, wellDone: 15 }, cues: { rare: '外层未吸汁', medium: '外层微软、内芯仍脆', wellDone: '全软吸汁' }, risk: '无生食风险，按口感选档', technique: '轻蘸快起，依口味调整', overtime: 'hard' },
    { name: '🧈 嫩豆腐', time: 120, desc: '小心易碎，烫热即可', times: { rare: 90, medium: 120, wellDone: 180 }, cues: { rare: '烫热', medium: '整体热透', wellDone: '更入味' }, risk: '小心易碎', technique: '小心易碎、烫热即可', overtime: 'hard' },
    { name: '🥠 千页豆腐', time: 120, desc: '略微膨胀，口感Q弹', times: { rare: 90, medium: 120, wellDone: 180 }, cues: { rare: '略微膨胀', medium: '膨胀、口感Q弹', wellDone: '更软' }, risk: '无生食风险，按口感选档', technique: '略微膨胀、口感Q弹', overtime: 'hard' },
    { name: '🥠 豆腐皮', time: 90, desc: '（干/鲜）软化吸汁', times: { rare: 60, medium: 90, wellDone: 120 }, cues: { rare: '软化', medium: '软化吸汁', wellDone: '软烂' }, risk: '', technique: '下锅软化吸汤即起', overtime: 'hard' },
    { name: '🥠 油炸腐竹', time: 240, desc: '吸饱汤汁，微软带韧', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '微软', medium: '吸汁、微软带韧', wellDone: '软烂' }, risk: '', technique: '捏压无坚硬内芯、表皮软滑', overtime: 'hard', midpoint: 0.5 },
    { name: '🍜 水晶粉丝', time: 120, desc: '变透明，柔软顺滑', times: { rare: 90, medium: 120, wellDone: 180 }, cues: { rare: '开始变透明', medium: '变透明、柔软顺滑', wellDone: '过软易断' }, risk: '无生食风险，按口感选档', technique: '变透明、柔软顺滑', overtime: 'hard' },
    { name: '🍜 土豆粉', time: 120, desc: '变透明，Q弹有嚼劲', times: { rare: 90, medium: 120, wellDone: 180 }, cues: { rare: '半透明', medium: '变透明、Q弹有嚼劲', wellDone: '软糯' }, risk: '无生食风险，按口感选档', technique: '白条变莹白半透、浮于汤面', overtime: 'hard', midpoint: 0.5 },
    { name: '🫓 苕皮', time: 180, desc: '（红薯粉皮）透明软糯', times: { rare: 120, medium: 180, wellDone: 240 }, cues: { rare: '开始透明', medium: '透明软糯', wellDone: '过软' }, risk: '无生食风险，按口感选档', technique: '变深色透明凝胶状、轻晃软弹', overtime: 'hard', midpoint: 0.5 },
    { name: '🍜 宽粉', time: 360, desc: '晶莹剔透，口感Q弹', times: { rare: 300, medium: 360, wellDone: 480 }, cues: { rare: '半透明', medium: '晶莹剔透、Q弹', wellDone: '软糯易夹断' }, risk: '无生食风险，按口感选档', technique: '煮至通体透明无白芯', overtime: 'hard', midpoint: 0.5 },
    { name: '🧊 冻豆腐', time: 180, desc: '吸饱汤汁，蜂窝明显', times: { rare: 150, medium: 180, wellDone: 240 }, cues: { rare: '开始吸汁', medium: '蜂窝明显、吸满汤', wellDone: '更软' }, risk: '', technique: '蜂窝孔洞充盈汤水、手感饱满', overtime: 'hard', midpoint: 0.5 },
    { name: '🍜 龙须面', time: 300, desc: '面条柔软，无硬心', times: { rare: 240, medium: 300, wellDone: 360 }, cues: { rare: '变软、微带硬心', medium: '柔软无硬心', wellDone: '软烂' }, risk: '无生食风险，按口感选档', technique: '面条柔软、无硬心', overtime: 'hard' },
    { name: '🍡 年糕', time: 300, desc: '软糯不粘牙', times: { rare: 240, medium: 300, wellDone: 360 }, cues: { rare: '开始变软', medium: '软糯不粘牙', wellDone: '软塌' }, risk: '无生食风险，按口感选档', technique: '浮于汤面按压有回弹', overtime: 'hard' },
    { name: '🥠 腐竹', time: 300, desc: '（干泡发）软韧入味', times: { rare: 240, medium: 300, wellDone: 360 }, cues: { rare: '变软', medium: '软韧入味', wellDone: '软烂' }, risk: '干品需泡发', technique: '捏压无坚硬内芯、表皮软滑', overtime: 'hard', midpoint: 0.5 },
    { name: '🍜 手工面', time: 300, desc: '面条熟透，劲道', times: { rare: 240, medium: 300, wellDone: 360 }, cues: { rare: '变软、微带硬心', medium: '熟透劲道', wellDone: '软烂' }, risk: '无生食风险，按口感选档', technique: '面条熟透、劲道', overtime: 'hard' },
    { name: '🍜 魔芋丝', time: 180, desc: '耐煮食材，多滚少许吸纳牛油辣味', times: { rare: 120, medium: 180, wellDone: 240 }, cues: { rare: '开始吸汁', medium: '多滚吸纳牛油辣味、软弹', wellDone: '更软' }, risk: '无生食风险，按口感选档', technique: '多滚少许吸纳牛油辣味', overtime: 'hard' },
    { name: '🥠 豆黄金', time: 15, desc: '极薄如纸，放滚汤内数秒打软吸汁即需捞出', times: { rare: 10, medium: 15, wellDone: 30 }, cues: { rare: '入汤未软', medium: '数秒打软吸汁', wellDone: '软烂' }, risk: '', technique: '滚汤内数秒打软吸汁即捞', overtime: 'hard' },
    { name: '🫓 油豆泡', time: 180, desc: '用漏勺将其压入汤中吸足红油膨胀，咬食小心内部热汤爆浆', times: { rare: 120, medium: 180, wellDone: 240 }, cues: { rare: '开始吸汁', medium: '压入汤中吸足红油膨胀', wellDone: '更软' }, risk: '小心内部热汤爆浆', technique: '漏勺压入汤中吸足红油', overtime: 'hard' },
    { name: '🍥 面筋球', time: 30, desc: '用筷子戳小洞压入沸油，快速吸附上层辣油与香气即起', times: { rare: 15, medium: 30, wellDone: 45 }, cues: { rare: '未吸汁', medium: '快速吸附上层辣油与香气', wellDone: '吸饱汤汁' }, risk: '', technique: '筷子戳小洞压入沸油', overtime: 'hard' },
    { name: '🍡 芝士年糕', time: 180, desc: '浮于汤面且变软，筷子按压表面有明显回弹和内部流心感', times: { rare: 120, medium: 180, wellDone: 240 }, cues: { rare: '开始变软', medium: '浮于汤面且变软、按压回弹', wellDone: '软塌' }, risk: '', technique: '浮于汤面按压有回弹', overtime: 'hard' },
  ],
  ball: [
    { name: '🍡 包心丸', time: 240, desc: '漂浮膨胀，内心熟透', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '漂浮膨胀', medium: '漂浮膨胀、内心热透', wellDone: '更紧实' }, risk: '包心类需确认内心热透', technique: '漂浮膨胀、内心熟透', overtime: 'hard' },
    { name: '🦐 虾丸', time: 240, desc: '漂浮变大，内部熟透', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '漂浮变大', medium: '漂浮变大、内部热透', wellDone: '更紧实' }, risk: '', technique: '漂浮变大、内部熟透', overtime: 'hard' },
    { name: '🐖 猪肉丸', time: 240, desc: '漂浮变色，按压有弹性', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '漂浮变色', medium: '漂浮变色、按压有弹性', wellDone: '更紧实' }, risk: '猪肉制品偏生未充分加热', technique: '漂浮变色、按压有弹性', overtime: 'hard' },
    { name: '🍢 四喜丸', time: 240, desc: '体积变大，浮起熟透', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '体积变大', medium: '体积变大、浮起', wellDone: '更紧实' }, risk: '肉丸需确认内部热透', technique: '体积变大、浮起熟透', overtime: 'hard' },
    { name: '🌿 香菜丸', time: 240, desc: '漂浮，香菜味浓郁', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '漂浮', medium: '漂浮、香菜味浓', wellDone: '更紧实' }, risk: '', technique: '漂浮、香菜味浓郁', overtime: 'hard' },
    { name: '🦑 墨鱼丸', time: 240, desc: '漂浮变白，Q弹爽口', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '漂浮变白', medium: '漂浮变白、Q弹爽口', wellDone: '更紧实' }, risk: '', technique: '漂浮变白、Q弹爽口', overtime: 'hard' },
    { name: '🥩 潮州牛肉丸', time: 240, desc: '弹性十足，内部多汁', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '漂浮变大', medium: '弹性十足、内部多汁', wellDone: '更紧实' }, risk: '', technique: '完全浮起并膨胀变大一圈', overtime: 'hard' },
    { name: '🍄 香菇贡丸', time: 240, desc: '漂浮，香菇可见', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '漂浮', medium: '漂浮、香菇可见', wellDone: '更紧实' }, risk: '', technique: '漂浮、香菇可见', overtime: 'hard' },
    { name: '💥 撒尿牛丸', time: 240, desc: '膨胀，小心烫嘴', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '膨胀', medium: '膨胀、爆汁', wellDone: '更紧实' }, risk: '小心烫嘴', technique: '膨胀、小心烫嘴', overtime: 'hard' },
    { name: '🐟 鱼丸', time: 240, desc: '漂浮变大，口感Q弹', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '漂浮变大', medium: '漂浮变大、口感Q弹', wellDone: '更紧实' }, risk: '', technique: '漂浮变大、口感Q弹', overtime: 'hard' },
    { name: '🥩 牛肉滑', time: 180, desc: '漂浮变色，紧实Q弹', times: { rare: 150, medium: 180, wellDone: 240 }, cues: { rare: '漂浮、变色大半', medium: '漂浮变色、紧实Q弹', wellDone: '更紧实' }, risk: '厚团需确认中心无粉色', technique: '浮起受热均匀、表面滑嫩', overtime: 'hard' },
    { name: '🦑 墨鱼滑', time: 180, desc: '漂浮变白，紧实Q弹', times: { rare: 150, medium: 180, wellDone: 240 }, cues: { rare: '漂浮变白', medium: '漂浮变白、紧实Q弹', wellDone: '更紧实' }, risk: '厚团需确认中心热透', technique: '滑团浮起、由暗灰变挺实', overtime: 'hard' },
    { name: '🦐 虾滑', time: 180, desc: '漂浮变红，紧实Q弹', times: { rare: 150, medium: 180, wellDone: 240 }, cues: { rare: '漂浮、中心微带粉', medium: '漂浮变红、紧实Q弹', wellDone: '更紧实' }, risk: '偏生中心可能带粉', technique: '勺挖成球下锅，完全浮起即捞', overtime: 'hard' },
    { name: '🦀 蟹黄鱼滑', time: 180, desc: '漂浮变色，蟹黄点缀', times: { rare: 150, medium: 180, wellDone: 240 }, cues: { rare: '漂浮、变色大半', medium: '漂浮变色、蟹黄点缀', wellDone: '更紧实' }, risk: '厚团需确认中心热透', technique: '漂浮变色、蟹黄点缀', overtime: 'hard' },
    { name: '🍄 金针菇卷', time: 180, desc: '牛肉变熟同时内部金针菇需充分受热熟透', times: { rare: 120, medium: 180, wellDone: 240 }, cues: { rare: '牛肉未变色', medium: '牛肉变熟、内部金针菇熟透软化', wellDone: '更紧实' }, risk: '厚团需确认中心热透', technique: '牛肉变熟同时金针菇熟透', overtime: 'hard' },
    { name: '🥩 牛肉丸', time: 360, desc: '受热完全膨胀浮起、筷子轻按有弹性阻力、咬开爆汁即成', times: { rare: 300, medium: 360, wellDone: 420 }, cues: { rare: '受热未膨胀', medium: '完全膨胀浮起、轻按有弹性阻力', wellDone: '更紧实' }, risk: '猪肉制品偏生未充分加热', technique: '完全膨胀浮起、轻按有弹性', overtime: 'hard' },
  ],
  other: [
    { name: '🥓 培根', time: 120, desc: '边缘卷曲，油脂溢出', times: { rare: 90, medium: 120, wellDone: 180 }, cues: { rare: '边缘开始卷曲', medium: '边缘卷曲、油脂溢出', wellDone: '更韧' }, risk: '腌制肉制品，建议全熟', technique: '边缘卷曲、油脂溢出', overtime: 'hard' },
    { name: '🍖 火腿', time: 120, desc: '（片状）烫热即可', times: { rare: 90, medium: 120, wellDone: 180 }, cues: { rare: '烫热', medium: '热透、脂边透明', wellDone: '更韧' }, risk: '熟制品，烫热即可', technique: '烫热即可、脂边透明', overtime: 'hard' },
    { name: '🥫 午餐肉', time: 120, desc: '边缘微焦更香', times: { rare: 90, medium: 120, wellDone: 180 }, cues: { rare: '边缘微变', medium: '边缘微焦更香', wellDone: '更韧' }, risk: '熟制品，烫热即可', technique: '表面浮起、边缘微胀', overtime: 'hard' },
    { name: '🦀 蟹肉棒', time: 90, desc: '（蟹柳）散开变色', times: { rare: 60, medium: 90, wellDone: 120 }, cues: { rare: '开始散开', medium: '散开变色', wellDone: '全散' }, risk: '制品需热透', technique: '丝纹微散微浮即出锅', overtime: 'hard' },
    { name: '🍥 鱼豆腐', time: 120, desc: '膨胀变软，Q弹', times: { rare: 90, medium: 120, wellDone: 180 }, cues: { rare: '开始膨胀', medium: '膨胀变软、Q弹', wellDone: '更软' }, risk: '', technique: '膨胀变软、Q弹', overtime: 'hard' },
    { name: '🌭 脆皮肠', time: 180, desc: '肠衣开裂，香气四溢', times: { rare: 150, medium: 180, wellDone: 240 }, cues: { rare: '肠衣开始裂', medium: '肠衣开裂、香气四溢', wellDone: '更韧' }, risk: '肉灌制品务必热透', technique: '肠衣开裂、香气四溢', overtime: 'hard' },
    { name: '🐟 乌鱼卷', time: 180, desc: '（非乌鱼片）变白卷曲', times: { rare: 150, medium: 180, wellDone: 240 }, cues: { rare: '变白卷曲', medium: '完全变白卷曲', wellDone: '变硬' }, risk: '水产建议全熟', technique: '变白卷曲', overtime: 'hard' },
    { name: '🥩 坨坨牛肉', time: 180, desc: '（预制）肉块热透入味', times: { rare: 150, medium: 180, wellDone: 240 }, cues: { rare: '热透', medium: '肉块热透入味', wellDone: '更软' }, risk: '预制块状需热透中心', technique: '肉块热透入味', overtime: 'hard' },
    { name: '🐟 巴沙鱼片', time: 300, desc: '鱼肉变白，完全熟透', times: { rare: 240, medium: 300, wellDone: 360 }, cues: { rare: '变白、中心微透', medium: '鱼肉完全变白、易碎分瓣', wellDone: '更紧' }, risk: '水产务必全熟', technique: '白肉微浮起轻掐断即熟', overtime: 'hard' },
    { name: '👅 鸭舌', time: 240, desc: '（鲜）表皮收缩起皱', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '表皮开始收缩', medium: '表皮收缩起皱', wellDone: '更韧' }, risk: '', technique: '舌尖受热外翻、舌根紧致', overtime: 'hard' },
    { name: '🐑 嫩羊肉', time: 300, desc: '（块状/厚片）内部无血色', times: { rare: 240, medium: 300, wellDone: 360 }, cues: { rare: '内部微带粉', medium: '内部无血色', wellDone: '发柴' }, risk: '块/厚片务必全熟', technique: '内部无血色', overtime: 'hard' },
    { name: '🍲 毛血旺', time: 300, desc: '（成品）整体烫热，食材入味', times: { rare: 240, medium: 300, wellDone: 360 }, cues: { rare: '整体热透', medium: '整体烫热、入味', wellDone: '更老' }, risk: '成品复热，鸭血需热透', technique: '整体烫热、食材入味', overtime: 'hard' },
    { name: '🥟 虾饺', time: 300, desc: '外皮透明，馅料浮起', times: { rare: 240, medium: 300, wellDone: 360 }, cues: { rare: '外皮开始透明', medium: '外皮透明、馅料浮起', wellDone: '皮塌' }, risk: '', technique: '外皮透明、馅料浮起', overtime: 'hard' },
    { name: '🦴 牛仔骨', time: 300, desc: '肉质离骨，酱香浓郁', times: { rare: 240, medium: 300, wellDone: 360 }, cues: { rare: '开始离骨', medium: '肉质离骨、酱香浓郁', wellDone: '更烂' }, risk: '', technique: '肉质离骨、酱香浓郁', overtime: 'hard' },
    { name: '🐔 鸡翅尖', time: 300, desc: '皮肉软糯，易脱骨', times: { rare: 240, medium: 300, wellDone: 360 }, cues: { rare: '皮肉开始软', medium: '皮肉软糯、易脱骨', wellDone: '更烂' }, risk: '禽类务必全熟', technique: '皮肉软糯、易脱骨', overtime: 'hard' },
    { name: '🐖 猪蹄', time: 360, desc: '（预制）皮糯肉烂，热透', times: { rare: 300, medium: 360, wellDone: 480 }, cues: { rare: '皮开始糯', medium: '皮糯肉烂、热透', wellDone: '更烂' }, risk: '预制需热透', technique: '中火浸煮至胶质黏嘴', overtime: 'hard', midpoint: 0.5 },
    { name: '🥟 蛋饺', time: 300, desc: '蛋皮吸汁，内馅熟透', times: { rare: 240, medium: 300, wellDone: 360 }, cues: { rare: '蛋皮吸汁', medium: '蛋皮吸汁、内馅热透', wellDone: '皮散' }, risk: '', technique: '蛋皮吸汁、内馅熟透', overtime: 'hard' },
    { name: '🐔 鸡翅中', time: 480, desc: '骨肉易分离，完全熟透', times: { rare: 420, medium: 480, wellDone: 540 }, cues: { rare: '开始脱骨', medium: '骨肉易分离、完全熟透', wellDone: '更烂' }, risk: '禽类务必全熟', technique: '骨肉易分离、完全熟透', overtime: 'hard' },
    { name: '🧠 脑花', time: 900, desc: '（猪脑花）无血丝呈固态，绵密', times: { rare: 720, medium: 900, wellDone: 1080 }, cues: { rare: '中心呈固态、无血丝', medium: '无血丝呈固态、绵密', wellDone: '更实' }, risk: '务必全熟（寄生虫风险）', technique: '漏勺中小火慢煨', overtime: 'hard', midpoint: 0.5 },
    { name: '🐔 无骨凤爪', time: 480, desc: '胶质软糯，晶莹剔透', times: { rare: 420, medium: 480, wellDone: 540 }, cues: { rare: '胶质开始软', medium: '胶质软糯、晶莹剔透', wellDone: '更烂' }, risk: '禽类务必全熟', technique: '沸汤透热后胶质化开', overtime: 'hard' },
    { name: '🦴 排骨', time: 480, desc: '（小块）肉质离骨，软烂入味', times: { rare: 420, medium: 480, wellDone: 540 }, cues: { rare: '开始离骨', medium: '肉质离骨、软烂入味', wellDone: '更烂' }, risk: '小块需全熟', technique: '深煮至筷子能扎透骨肉', overtime: 'hard', midpoint: 0.5 },
    { name: '🥮 响铃卷', time: 5, desc: '筷子夹住沉入浓汤3秒快速打个滚即捞', times: { rare: 3, medium: 5, wellDone: 6 }, cues: { rare: '入汤未吸汁', medium: '沉入浓汤3秒打个滚、秒吸汤汁', wellDone: '吸饱汤汁、微脆转软' }, risk: '', technique: '沉入浓汤3秒打个滚即捞', overtime: 'hard' },
    { name: '🐔 鸡爪', time: 900, desc: '生爪肉厚，需开锅即下、久煨慢煮至外皮软烂裂口', times: { rare: 600, medium: 900, wellDone: 1200 }, cues: { rare: '外皮未软', medium: '外皮软烂裂口', wellDone: '更烂' }, risk: '禽类务必全熟', technique: '开锅即下、久煨慢煮', overtime: 'hard', midpoint: 0.5 },
    { name: '🍥 鱼籽福袋', time: 300, desc: '外层豆皮完全变软膨大、内部鱼籽肉馅滚烫受热熟透', times: { rare: 240, medium: 300, wellDone: 360 }, cues: { rare: '外层豆皮未软', medium: '外层豆皮完全变软膨大、内部滚烫', wellDone: '更软' }, risk: '包心类需确认内心热透', technique: '外层豆皮变软膨大、内部滚烫', overtime: 'hard' },
    { name: '🐔 鸭掌', time: 240, desc: '已熟制的脱骨鸭掌，沸汤透热后胶质化开，入口即化软烂', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '胶质开始软', medium: '胶质软糯、晶莹剔透', wellDone: '更烂' }, risk: '禽类务必全熟', technique: '沸汤透热后胶质化开', overtime: 'hard' },
    { name: '🌭 甜香肠', time: 240, desc: '肠体两头爆裂开花、表皮微胀焦亮即可，甜咸爆汁', times: { rare: 180, medium: 240, wellDone: 300 }, cues: { rare: '肠体未胀', medium: '肠体两头爆裂开花、表皮微胀焦亮', wellDone: '更韧' }, risk: '肉灌制品务必热透', technique: '肠体两头爆裂开花即捞', overtime: 'hard' },
  ],
};
